# Generated by Django 3.1.7 on 2021-09-03 23:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20210903_1138'),
        ('billing', '0002_auto_20210902_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BellingProfile',
            new_name='BillingProfile',
        ),
    ]
