# Generated by Django 3.1.7 on 2022-02-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='enden',
            new_name='ended',
        ),
    ]
