# Generated by Django 3.1.7 on 2021-06-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.FloatField(default=0.0, max_length=20),
        ),
    ]
