# Generated by Django 3.1.7 on 2021-09-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210903_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='belling_profile',
            new_name='billing_profile',
        ),
    ]
