# Generated by Django 3.2 on 2021-04-30 00:10

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210429_1823'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
